server:
  port: 20000
spring:
  application:
    name: qmcc-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20000/eureka
    register-with-eureka: false
    fetch-registry: false