server:
  port: 20001
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///bisheqmcc
    username: root
    password: nyc123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 10 #过期时间
mybatis:
  type-aliases-package: com.qmcc.item.pojo